/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { FriendRequest } from "./FriendRequest";
import { FriendRequestCountArgs } from "./FriendRequestCountArgs";
import { FriendRequestFindManyArgs } from "./FriendRequestFindManyArgs";
import { FriendRequestFindUniqueArgs } from "./FriendRequestFindUniqueArgs";
import { CreateFriendRequestArgs } from "./CreateFriendRequestArgs";
import { UpdateFriendRequestArgs } from "./UpdateFriendRequestArgs";
import { DeleteFriendRequestArgs } from "./DeleteFriendRequestArgs";
import { FriendRequestService } from "../friendRequest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => FriendRequest)
export class FriendRequestResolverBase {
  constructor(
    protected readonly service: FriendRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FriendRequest",
    action: "read",
    possession: "any",
  })
  async _friendRequestsMeta(
    @graphql.Args() args: FriendRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [FriendRequest])
  @nestAccessControl.UseRoles({
    resource: "FriendRequest",
    action: "read",
    possession: "any",
  })
  async friendRequests(
    @graphql.Args() args: FriendRequestFindManyArgs
  ): Promise<FriendRequest[]> {
    return this.service.friendRequests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => FriendRequest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FriendRequest",
    action: "read",
    possession: "own",
  })
  async friendRequest(
    @graphql.Args() args: FriendRequestFindUniqueArgs
  ): Promise<FriendRequest | null> {
    const result = await this.service.friendRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => FriendRequest)
  @nestAccessControl.UseRoles({
    resource: "FriendRequest",
    action: "create",
    possession: "any",
  })
  async createFriendRequest(
    @graphql.Args() args: CreateFriendRequestArgs
  ): Promise<FriendRequest> {
    return await this.service.createFriendRequest({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => FriendRequest)
  @nestAccessControl.UseRoles({
    resource: "FriendRequest",
    action: "update",
    possession: "any",
  })
  async updateFriendRequest(
    @graphql.Args() args: UpdateFriendRequestArgs
  ): Promise<FriendRequest | null> {
    try {
      return await this.service.updateFriendRequest({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FriendRequest)
  @nestAccessControl.UseRoles({
    resource: "FriendRequest",
    action: "delete",
    possession: "any",
  })
  async deleteFriendRequest(
    @graphql.Args() args: DeleteFriendRequestArgs
  ): Promise<FriendRequest | null> {
    try {
      return await this.service.deleteFriendRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
