/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ChatRoom } from "./ChatRoom";
import { ChatRoomCountArgs } from "./ChatRoomCountArgs";
import { ChatRoomFindManyArgs } from "./ChatRoomFindManyArgs";
import { ChatRoomFindUniqueArgs } from "./ChatRoomFindUniqueArgs";
import { CreateChatRoomArgs } from "./CreateChatRoomArgs";
import { UpdateChatRoomArgs } from "./UpdateChatRoomArgs";
import { DeleteChatRoomArgs } from "./DeleteChatRoomArgs";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { User } from "../../user/base/User";
import { ChatRoomService } from "../chatRoom.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ChatRoom)
export class ChatRoomResolverBase {
  constructor(
    protected readonly service: ChatRoomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "read",
    possession: "any",
  })
  async _chatRoomsMeta(
    @graphql.Args() args: ChatRoomCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ChatRoom])
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "read",
    possession: "any",
  })
  async chatRooms(
    @graphql.Args() args: ChatRoomFindManyArgs
  ): Promise<ChatRoom[]> {
    return this.service.chatRooms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ChatRoom, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "read",
    possession: "own",
  })
  async chatRoom(
    @graphql.Args() args: ChatRoomFindUniqueArgs
  ): Promise<ChatRoom | null> {
    const result = await this.service.chatRoom(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ChatRoom)
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "create",
    possession: "any",
  })
  async createChatRoom(
    @graphql.Args() args: CreateChatRoomArgs
  ): Promise<ChatRoom> {
    return await this.service.createChatRoom({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ChatRoom)
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "update",
    possession: "any",
  })
  async updateChatRoom(
    @graphql.Args() args: UpdateChatRoomArgs
  ): Promise<ChatRoom | null> {
    try {
      return await this.service.updateChatRoom({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ChatRoom)
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "delete",
    possession: "any",
  })
  async deleteChatRoom(
    @graphql.Args() args: DeleteChatRoomArgs
  ): Promise<ChatRoom | null> {
    try {
      return await this.service.deleteChatRoom(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Message], { name: "messages" })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async findMessages(
    @graphql.Parent() parent: ChatRoom,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: ChatRoom): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
